let showData = [
  {date: "02/08/2020", city: "Lancaster, PA", venue: "The Kaleidoscope", artists: "James Barrett, Cory Paternoster, Seasonal", url:"img/flyers/02-07-08-2020.jpg"},
  {date: "02/07/2020", city: "Scranton, PA", venue: "Stage West", artists: "James Barrett, Cory Paternoster, Garden View", url:"img/flyers/02-07-08-2020.jpg"},
  {date: "01/03/2020", city: "Brooklyn, NY", venue: "The Monitor (House Show)", artists: "Lupia, Mallory Hawk, Waterfall Strainer, Oh, Madeline"},
  {date: "04/30/2018", city: "Lancaster, PA", venue: "The Kaleidoscope", artists: "Sinai Vessel, Sammy Heck"},
  {date: "02/09/2018", city: "Harrisburg, PA", venue: "River City Blues", artists: "Sun Not Yellow, November Lounge", url:"img/flyers/02-09-2018.jpg"},
  {date: "01/27/2018", city: "Lancaster, PA", venue: "The Kaleidoscope", artists: "Jake Clarke, Cherry, Witch Bomb", url:"img/flyers/01-27-2018.jpg"},
  {date: "01/18/2018", city: "Lancaster, PA", venue: "Moira Lazarus", artists: "Honeyfitz, The Ok Ok's, Sun Not Yellow", url:"img/flyers/01-18-2018.jpg"},
  {date: "05/31/2017", city: "Mount Joy, PA", venue: "Bube's Brewery", artists: "The Weak Days, Emperor Penguin"},
  {date: "05/07/2017", city: "Harrisburg, PA", venue: "Harrisburg Midtown Arts Center", artists: "Pinegrove, Russel the Leaf"},
  {date: "03/26/2017", city: "Lancaster, PA", venue: "Lizard Lounge", artists: "Hodera, City Cop, Seasonal, Alomar"},
  {date: "03/19/2017", city: "Lancaster, PA", venue: "Lizard Lounge", artists: "Sleepy Limbs, Dollys"},
  {date: "03/11/2017", city: "York, PA", venue: "The Shop", artists: "Shut Up, Mouth, Sleepy Limbs, The Hawkshaws, The Great Heights Band"},
  {date: "01/27/2017", city: "Philadelphia, PA", venue: "JJ's Diner", artists: "The Mellowells, Caracara, Grayling", url:"img/flyers/01-27-2017.jpg"},
  {date: "12/16/2016", city: "Lancaster, PA", venue: "Fulton Street Co-op", artists: "Thin Lips, Spill, Seasonal", url:"img/flyers/12-16-2016.jpg"},
  {date: "08/24/2016", city: "Mount Joy, PA", venue: "Bube's Brewery", artists: "Buffalo Rodeo, Who Loves You, Lupia", url:"img/flyers/08-24-2016.jpg"},
  {date: "08/06/2016", city: "Wilkes-Barre, PA", venue: "The Other Side", artists: "Old Charades, Jared Hart, Those Clever Foxes, 18th & Addison, Embera, Black Hole Heart, Sheep Morale", url:"img/flyers/08-06-2016.jpg"},
  {date: "08/03/2016", city: "Lancaster, PA", venue: "Beat Mountain", artists: "The Year End, Port Ellis, Lupia, Narrowed"},
  {date: "07/08/2016", city: "Shickshinny, PA", venue: "Yardstock", artists: "Esta Coda, Hodera, Wander, and more", url:"img/flyers/07-08-2016.jpg"},
  {date: "06/24/2016", city: "Wilkes-Barre, PA", venue: "The Other Side", artists: "Embera, F.M. Waves, Sean Hamilton Walsh", url:"img/flyers/06-24-2016.jpg"},
  {date: "06/17/2016", city: "Lancaster, PA", venue: "Beat Mountain", artists: "The Mellowells, Seasonal, Lupia"},
  {date: "06/10/2016", city: "Scranton, PA", venue: "The Keys", artists: "Black Hole Heart, Old Charades, Purcell"},
  {date: "05/21/2016", city: "Kunkletown, PA", venue: "Platform 9 3/4 House", artists: "Hodera, The Year End, The Greater Victory", url:"img/flyers/05-21-2016.jpg"},
  {date: "05/02/2016", city: "Philadelphia, PA", venue: "The Pharmacy", artists: "Steveo & The Crippling Addications, Turnspit, Lauren Denitzio (Worriers)"},
  {date: "04/10/2016", city: "Lancaster, PA", venue: "Beat Mountain", artists: "No Stranger, Magnolia., Guilt Trip"},
  {date: "04/10/2016", city: "Lancaster, PA", venue: "Beat Mountain", artists: "No Stranger, Magnolia., Guilt Trip"},
  {date: "04/02/2016", city: "Wilkes-Barre, PA", venue: "The Other Side", artists: "Old Charades, Pity Party, Black Hole Heart, Sheep Morale"},
  {date: "03/09/2016", city: "Lancaster, PA", venue: "Ursa Lunar", artists: "Paradrei, Lupia, Spur"},
  {date: "02/27/2016", city: "Wilkes-Barre, PA", venue: "The Other Side", artists: "Better Days, Coping Skills, James Barrett, Centralia Moving Co.", url:"img/flyers/02-27-2016.jpg"},
  {date: "01/16/2016", city: "Allentown, PA", venue: "Coffee House Without Limits", artists: "Friends in Distraction, Better Days, Toy Cars, Wishing Well"},
  {date: "12/06/2015", city: "Lancaster, PA", venue: "Beat Mountain", artists: "Author, Magnolia., Only Sibling"},
  {date: "12/05/2015", city: "Wilkes-Barre, PA", venue: "The Other Side", artists: "Esta Coda, Old Charades, Final Descent, Social Loafers, Moral Code"},
  {date: "10/23/2015", city: "Annville, PA", venue: "LVC", artists: "Oh Great Mississippi, The Mellowells, Whaler, Lupia", url:"img/flyers/10-23-2015.jpg"},
  {date: "09/26/2015", city: "Scott Township, PA", venue: "House Show", artists: "Lee Corey Oswald, Soda Bomb, Give Us Your Bones, Cheap Seats, Maniac, The Sane", url:"img/flyers/09-26-2015.jpg"},
  {date: "09/18/2015", city: "Lancaster, PA", venue: "Art & Glassworks", artists: "Seasonal, Ethan McDonnell", url:"img/flyers/09-18-2015.jpg"},
  {date: "09/05/2015", city: "Stroudsburg, PA", venue: "The Living Room", artists: "Off & On, Hey Anna, The Red Pandas, chrysalis", url:"img/flyers/09-05-2015.jpg"},
  {date: "08/09/2015", city: "Wilkes-Barre, PA", venue: "The Other Side", artists: "Those Clever Foxes, Esta Coda, Old Charades, Emma Karchner, Embera, Purcell"},
  {date: "07/21/2015", city: "Philadelphia, PA", venue: "Kung Fu Necktie", artists: "Absolute Sky, The Serotones, The Mellowells"},
  {date: "05/02/2015", city: "Annville, PA", venue: "LVC", artists: "Houses, Gardens release show: The Mellowells, Oh Great Mississippi, The Goodmen, Lupia"},
  {date: "04/25/2015", city: "Annville, PA", venue: "LVC", artists: "Valleyfest 2015: The Mellowells, Oh Great Mississippi, and more"},
  {date: "12/06/2014", city: "Annville, PA", venue: "LVC", artists: "The Mellowells, Paradrei, Exit Salida, Oh Great Mississippi"},
  {date: "07/05/2014", city: "Effort, PA", venue: "Castle Weird Skull", artists: "Captain, We're Sinking!, The Holy Mess, Wicca Phase Springs Eternal", url:"img/flyers/07-05-2014.jpg"},
  {date: "02/22/2014", city: "Annville, PA", venue: "JDCafe422", artists: "Author (The Mellowells), Exit Salida, Dean Howey", url:"img/flyers/02-22-2014.jpg"},
  {date: "01/17/2014", city: "Easton, PA", venue: "Quadrant Book Shop", artists: "Explorers, Glassgrade, Forestmate, If You Will", url:"img/flyers/01-17-2014.jpg"},
  {date: "12/29/2013", city: "Philadelphia, PA", venue: "Kung Fu Necktie", artists: "Gatherings, The Brooklyn What, Pine Barons"},
  {date: "12/28/2013", city: "Stroudsburg, PA", venue: "The Living Room", artists: "Author (The Mellowells), Flak Rabbit, and more"},
  {date: "11/16/2013", city: "Annville, PA", venue: "JDCafe422", artists: "Paradrei, The Engine Atlantic, Author (The Mellowells)", url:"img/flyers/11-16-2013.jpg"},
  {date: "09/21/2013", city: "Easton, PA", venue: "House Show", artists: "Jules Verne, Midland City, Octopus Logic, K.I.R.", url:"img/flyers/09-21-2013.jpg"},
  {date: "09/20/2013", city: "Easton, PA", venue: "Quadrant Book Shop", artists: "Midland City, The Soviet, mountaineer., If You Will", url:"img/flyers/09-20-2013.jpg"},
  {date: "09/14/2013", city: "Effort, PA", venue: "Castle Weird Skull", artists: "Ark Royal, Rob, Lately, Starving the Tsunami, and more"},
  {date: "06/08/2013", city: "Blairstown, NJ", venue: "Historic Blairstown Theater", artists: "The Soviet, Midland City", url:"img/flyers/06-08-2013.jpg"},
]
